### ISSUE TITLE
Tips about broadcasting

### ISSUE THREAD

**Issue by sosiristseng** [DANTA-HOJA/MMSB2022_HW1#1]
In this line
https://github.com/DANTA-HOJA/MMSB2022_HW1/blob/87700305a78e2870056a656e6fe3ab75a8d9faa1/Part3-1_The_RK4_method.jl#L11

you could write

```julia
return @. u + (k1 + 2*k2 + 2*k3 + k4)/6
```
to make all arithmetic operations broadcast on each element.

**Comment by DANTA-HOJA** [comment]
thank you, \(^_^)/
